// Auto-generated by build-shader-js.py. Wraps the raw Shadertoy GLSL
// source so it can be loaded as a classic <script> (no modules,
// no fetch). Exposes window.SHADER_<ID> = { id, title, author, channels, source }.
// To see just the reflection (no refraction/transmission) uncomment this next line:
//#define REFLECTANCE_ONLY
// performance and raymarching options
// optical properties
// iq's cubemap function
// iq's 3D noise function
// a sphere with a little bit of warp
// sample weights for the cubemap given a wavelength i
// room for improvement in this function
// downsample to RGB
// compute the wavelength/IOR curve values.
window.SHADER_ld3SDl = {
  "id": "ld3SDl",
  "title": "Fast Thin-Film Interference",
  "scenes": ["own"],
  "group": "orig",
  "url": "https://www.shadertoy.com/view/ld3SDl",
  "camDist": 6.5,
  "camPitch": 0.0,
  "channels": {"0":"env_cube","1":"thickness","2":"noise","3":"noise"},
  "vars": [
    { "name": "uCamPos", "type": "vec3", "feed": "camPos" },
    { "name": "uCamRt", "type": "vec3", "feed": "camRt" },
    { "name": "uCamUp", "type": "vec3", "feed": "camUp" },
    { "name": "uCamFw", "type": "vec3", "feed": "camFw" }
  ],
  "params": [
    { "name": "uFov", "type": "float", "label": "fov", "group": "camera", "min": 30, "max": 110, "step": 0.5, "def": 67.38013505195957, "hint": "vertical field of view in degrees (default = the original's 1.5 lens length)" },
    { "name": "uIterations", "type": "int", "label": "steps", "group": "march", "min": 1, "max": 64, "step": 1, "def": 20, "hint": "raymarch step budget (uniform loop bound, keeps the driver from unrolling)" },
    { "name": "uAASamples", "type": "int", "label": "aa", "group": "march", "min": 1, "max": 8, "step": 1, "def": 1, "hint": "anti-alias samples around each pixel (uniform loop bound, keeps the driver from unrolling)" },
    { "name": "uEps", "type": "float", "label": "eps", "group": "march", "min": 0.001, "max": 0.05, "step": 0.001, "def": 0.01, "hint": "raymarch intersection precision, also the SDF-normal delta" },
    { "name": "uBound", "type": "float", "label": "bound", "group": "march", "min": 2.0, "max": 12.0, "step": 0.5, "def": 6.0, "hint": "cube bounds check around the origin" },
    { "name": "uDistScale", "type": "float", "label": "dist scale", "group": "march", "min": 0.3, "max": 1.5, "step": 0.05, "def": 0.9, "hint": "fraction of the SDF step taken per iteration (conservative under-step)" },
    { "name": "uDispersion", "type": "float", "label": "dispersion", "group": "optics", "min": 0.0, "max": 0.3, "step": 0.005, "def": 0.05, "hint": "chromatic dispersion amount" },
    { "name": "uIor", "type": "float", "label": "ior", "group": "optics", "min": 1.0, "max": 2.0, "step": 0.01, "def": 1.0, "hint": "base index of refraction, as a ratio" },
    { "name": "uThickScale", "type": "float", "label": "film scale", "group": "optics", "min": 0.0, "max": 200.0, "step": 1.0, "def": 32.0, "hint": "film thickness scaling factor" },
    { "name": "uThickCube", "type": "float", "label": "film cube scale", "group": "optics", "min": 0.0, "max": 1.0, "step": 0.005, "def": 0.1, "hint": "film thickness cubemap scaling factor" },
    { "name": "uReflScale", "type": "float", "label": "reflectance", "group": "optics", "min": 0.0, "max": 8.0, "step": 0.1, "def": 3.0, "hint": "reflectance scaling factor" },
    { "name": "uReflGamma", "type": "float", "label": "refl gamma", "group": "optics", "min": 0.0, "max": 6.0, "step": 0.1, "def": 2.0, "hint": "reflectance gamma scaling factor" },
    { "name": "uFresnel", "type": "float", "label": "fresnel", "group": "optics", "min": 0.0, "max": 1.0, "step": 0.01, "def": 0.7, "hint": "fresnel weight for reflectance" },
    { "name": "uContrast", "type": "float", "label": "contrast", "group": "grade", "min": 0.5, "max": 40.0, "step": 0.5, "def": 8.0, "hint": "sigmoid contrast enhancement" },
    { "name": "uGammaCurve", "type": "float", "label": "curve", "group": "grade", "min": 5.0, "max": 400.0, "step": 5.0, "def": 50.0, "hint": "filmic gamma curve constant" },
    { "name": "uGammaScale", "type": "float", "label": "gamma", "group": "grade", "min": 0.5, "max": 10.0, "step": 0.1, "def": 4.5, "hint": "filmic gamma scale" },
    { "name": "uGreenWeight", "type": "float", "label": "green weight", "group": "grade", "min": 0.5, "max": 8.0, "step": 0.1, "def": 2.8, "hint": "green weight when resampling the 6 wavelengths down to RGB" }
  ],
  "source":
`/*
	Fast Thin-Film Interference

	This is a performance-optimized version of my previous 
	thin-film interference shader here: https://www.shadertoy.com/view/XddXRj
	This version also fixes a platform-specific bug and has
	a few other tweaks as well.

	Thin-film interference and chromatic dispersion are simulated at
	six different wavelengths and then downsampled to RGB.
*/


// The original tunables (#defines) are uniforms driven by the GUI — the
// metadata above lists every one. Only the structurally fixed ones stay as
// constants: TWO_PI, WAVELENGTHS (array size) and ITERATIONS (compile-time
// cap for the uniform loop bound).
#define ITERATIONS 64
#define TWO_PI 6.28318530718
#define WAVELENGTHS 6

vec3 fancyCube( sampler2D sam, in vec3 d, in float s, in float b )
{
    vec3 colx = textureLod( sam, 0.5 + s*d.yz/d.x, b ).xyz;
    vec3 coly = textureLod( sam, 0.5 + s*d.zx/d.y, b ).xyz;
    vec3 colz = textureLod( sam, 0.5 + s*d.xy/d.z, b ).xyz;
    
    vec3 n = d*d;
    
    return (colx*n.x + coly*n.y + colz*n.z)/(n.x+n.y+n.z);
}

float hash( float n ){
    return fract(sin(n)*43758.5453);
}

float noise( in vec3 x ) {
    vec3 p = floor(x);
    vec3 f = fract(x);

    f = f*f*(3.0-2.0*f);
    float n = p.x + p.y*57.0 + 113.0*p.z;
    return mix(mix(mix( hash(n+  0.0), hash(n+  1.0),f.x),
                   mix( hash(n+ 57.0), hash(n+ 58.0),f.x),f.y),
               mix(mix( hash(n+113.0), hash(n+114.0),f.x),
                   mix( hash(n+170.0), hash(n+171.0),f.x),f.y),f.z);
}

vec3 noise3(vec3 x) {
	return vec3( noise(x+vec3(123.456,.567,.37)),
				 noise(x+vec3(.11,47.43,19.17)),
				 noise(x) );
}

float sdf( vec3 p ) {
	vec3 n = vec3(sin(iDate.w * 0.5), sin(iDate.w * 0.3), cos(iDate.w * 0.2));
	vec3 q = 0.1 * (noise3(p + n) - 0.5);
  
	return length(q + p) - 3.5;
}

vec3 fresnel( vec3 rd, vec3 norm, vec3 n2 ) {
   vec3 r0 = pow((1.0-n2)/(1.0+n2), vec3(2));
   return r0 + (1. - r0)*pow(clamp(1. + dot(rd, norm), 0.0, 1.0), 5.);
}

vec3 calcNormal( in vec3 pos ) {
    const vec3 v1 = vec3( 1.0,-1.0,-1.0);
    const vec3 v2 = vec3(-1.0,-1.0, 1.0);
    const vec3 v3 = vec3(-1.0, 1.0,-1.0);
    const vec3 v4 = vec3( 1.0, 1.0, 1.0);

	return normalize( v1*sdf( pos + v1*uEps ) + 
					  v2*sdf( pos + v2*uEps ) + 
					  v3*sdf( pos + v3*uEps ) + 
					  v4*sdf( pos + v4*uEps ) );
}

vec3 filmic_gamma(vec3 x) {
	return log(uGammaCurve * x + 1.0) / uGammaScale;    
}

vec3 filmic_gamma_inverse(vec3 y) {
	return (1.0 / uGammaCurve) * (exp(uGammaScale * y) - 1.0); 
}

vec3 texCubeSampleWeights(float i) {
	vec3 w = vec3((1.0 - i) * (1.0 - i), uGreenWeight * i * (1.0 - i), i * i);
    return w / dot(w, vec3(1.0));
}

vec3 sampleCubeMap(vec3 i, vec3 rd) {
	vec3 col = textureLod(iChannel0, rd * vec3(1.0,-1.0,1.0), 0.0).xyz; 
    return vec3(
        dot(texCubeSampleWeights(i.x), col),
        dot(texCubeSampleWeights(i.y), col),
        dot(texCubeSampleWeights(i.z), col)
    );
}

vec3 sampleCubeMap(vec3 i, vec3 rd0, vec3 rd1, vec3 rd2) {
	vec3 col0 = textureLod(iChannel0, rd0 * vec3(1.0,-1.0,1.0), 0.0).xyz;
    vec3 col1 = textureLod(iChannel0, rd1 * vec3(1.0,-1.0,1.0), 0.0).xyz; 
    vec3 col2 = textureLod(iChannel0, rd2 * vec3(1.0,-1.0,1.0), 0.0).xyz; 
    return vec3(
        dot(texCubeSampleWeights(i.x), col0),
        dot(texCubeSampleWeights(i.y), col1),
        dot(texCubeSampleWeights(i.z), col2)
    );
}



vec3 sampleWeights(float i) {
	return vec3((1.0 - i) * (1.0 - i), uGreenWeight * i * (1.0 - i), i * i);
}

vec3 resample(vec3 wl0, vec3 wl1, vec3 i0, vec3 i1) {
	vec3 w0 = sampleWeights(wl0.x);
    vec3 w1 = sampleWeights(wl0.y);
    vec3 w2 = sampleWeights(wl0.z);
    vec3 w3 = sampleWeights(wl1.x);
    vec3 w4 = sampleWeights(wl1.y);
    vec3 w5 = sampleWeights(wl1.z);
    
    return i0.x * w0 + i0.y * w1 + i0.z * w2
         + i1.x * w3 + i1.y * w4 + i1.z * w5;
}

vec3 resampleColor(vec3[WAVELENGTHS] rds, vec3 refl0, vec3 refl1, vec3 wl0, vec3 wl1) {

    
    #ifdef REFLECTANCE_ONLY
    	vec3 intensity0 = refl0;
    	vec3 intensity1 = refl1;
    #else
        vec3 cube0 = sampleCubeMap(wl0, rds[0], rds[1], rds[2]);
    	vec3 cube1 = sampleCubeMap(wl1, rds[3], rds[4], rds[5]);
    
        vec3 intensity0 = filmic_gamma_inverse(cube0) + refl0;
    	vec3 intensity1 = filmic_gamma_inverse(cube1) + refl1;
    #endif
    vec3 col = resample(wl0, wl1, intensity0, intensity1);

    return 1.4 * filmic_gamma(col / float(WAVELENGTHS));
}

vec3 resampleColorSimple(vec3 rd, vec3 wl0, vec3 wl1) {
    vec3 cube0 = sampleCubeMap(wl0, rd);
    vec3 cube1 = sampleCubeMap(wl1, rd);
    
    vec3 intensity0 = filmic_gamma_inverse(cube0);
    vec3 intensity1 = filmic_gamma_inverse(cube1);
    vec3 col = resample(wl0, wl1, intensity0, intensity1);

    return 1.4 * filmic_gamma(col / float(WAVELENGTHS));
}

vec3 iorCurve(vec3 x) {
	return x;
}

vec3 attenuation(float filmThickness, vec3 wavelengths, vec3 normal, vec3 rd) {
	return 0.5 + 0.5 * cos(((uThickScale * filmThickness)/(wavelengths + 1.0)) * dot(normal, rd));    
}

vec3 contrast(vec3 x) {
	return 1.0 / (1.0 + exp(-uContrast * (x - 0.5)));    
}

// Camera comes from the shared orbit rig (js/camera.js): uCamPos + basis.
// The projection keeps the original's look-at matrix; the "lens length" 1.5
// is the cotangent of half the FOV, so uFov maps onto it (default 67.38°).
mat3 calcLookAtMatrix( in vec3 ro, in vec3 ta, in float roll )
{
    vec3 ww = normalize( ta - ro );
    vec3 uu = normalize( cross(ww,vec3(sin(roll),cos(roll),0.0) ) );
    vec3 vv = normalize( cross(uu,ww));
    return mat3( uu, vv, ww );
}

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    vec2 p = (-iResolution.xy + 2.0*fragCoord.xy)/iResolution.y;

    vec3 ro = uCamPos;
    mat3 camMat = calcLookAtMatrix( ro, ro + uCamFw, 0.0 );
    float lens = 1.0 / tan (radians (uFov) * 0.5);

    float dh = (0.666 / iResolution.y);

    vec3 col = vec3(0.0);

    vec3 wavelengths0 = vec3(1.0, 0.8, 0.6);
    vec3 wavelengths1 = vec3(0.4, 0.2, 0.0);
    vec3 iors0 = uIor + iorCurve(wavelengths0) * uDispersion;
    vec3 iors1 = uIor + iorCurve(wavelengths1) * uDispersion;

    vec3 rds[WAVELENGTHS];

    // uniform-driven bounds keep the loops real (ANGLE's HLSL translator
    // would unroll constant-bound loops into a multi-second link)
    int maxIter = min(max(uIterations, 1), ITERATIONS);
    int aa = max(uAASamples, 1);
    float rads = TWO_PI / float(aa);
    for (int samp = 0; samp < aa; samp++) {
        vec2 dxy = dh * vec2(cos(float(samp) * rads), sin(float(samp) * rads));
        vec3 rd = normalize(camMat * vec3(p.xy + dxy, lens));
		vec3 pos = ro;
        bool hit = false;
        for (int j = 0; j < maxIter; j++) {
            float t = uDistScale * sdf(pos);
            pos += t * rd;
            hit = t < uEps;
            if ( clamp(pos, -uBound, uBound) != pos || hit ) {
                break;
            }
        }

        if (hit) {
            vec3 normal = calcNormal(pos);

            float filmThickness = fancyCube( iChannel1, normal, uThickCube, 0.0 ).x + 0.1;

            vec3 att0 = attenuation(filmThickness, wavelengths0, normal, rd);
            vec3 att1 = attenuation(filmThickness, wavelengths1, normal, rd);

            vec3 f0 = (1.0 - uFresnel) + uFresnel * fresnel(rd, normal, 1.0 / iors0);
            vec3 f1 = (1.0 - uFresnel) + uFresnel * fresnel(rd, normal, 1.0 / iors1);

            vec3 rrd = reflect(rd, normal);

            vec3 cube0 = uReflGamma * att0 * sampleCubeMap(wavelengths0, rrd);
            vec3 cube1 = uReflGamma * att1 * sampleCubeMap(wavelengths1, rrd);

            vec3 refl0 = uReflScale * filmic_gamma_inverse(mix(vec3(0), cube0, f0));
            vec3 refl1 = uReflScale * filmic_gamma_inverse(mix(vec3(0), cube1, f1));

            rds[0] = refract(rd, normal, iors0.x);
            rds[1] = refract(rd, normal, iors0.y);
            rds[2] = refract(rd, normal, iors0.z);
            rds[3] = refract(rd, normal, iors1.x);
            rds[4] = refract(rd, normal, iors1.y);
            rds[5] = refract(rd, normal, iors1.z);

            col += resampleColor(rds, refl0, refl1, wavelengths0, wavelengths1);
        } else {
        	col += resampleColorSimple(rd, wavelengths0, wavelengths1);    
        }

    }
    
    col /= float(aa);
	   
    fragColor = vec4( contrast(col), 1.0 );
}`,
};
